services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always

  youtube-sentiment-frontend:
    build:
      context: .
      dockerfile: youtube-sentiment-frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./youtube-sentiment-frontend:/app
    restart: always
